import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About | Ray's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>About</a>
        </h1>
      </main>
    </div>
  )
}
