import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Blog() {
  return (
    <div className={styles.container}>
      <Head>
        <title> Blog | Ray's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3 className={styles.title}>
          Welcome to <a>My Blog Page!</a>
        </h3>
        <h4> Coming soon! </h4>
        <h5> This website is a work in process. I am still working on this site </h5>

        
      </main>

    </div>
  )
}
